---
title: "HumanMyocarditis"
author: "A.DeMartin"
date: "2024-07-18"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
library(RColorBrewer)
```

############################## start pre-processing ##############################

## load files and merge
```{r load files, eval=FALSE, include=TRUE}
### load files healthy donors and merge
basedir <- "/Users/immbio/Desktop/Project/Angelina/HumanMyocarditis/data/healthyDonors/"
fileNamList <- list.files(path = basedir)

for(i in 1:length(fileNamList)){
  seuratS <- readRDS(paste0(basedir, fileNamList[i]))
  if(exists("seuratM")){
    seuratM <- merge(x = seuratM, y = seuratS)
  }else{
    seuratM <- seuratS
  }
}

remove(seuratS)
table(seuratM$dataset)
table(seuratM$orig.ident)

### load files dataJune24 and merge
basedir <- "/Users/immbio/Desktop/Project/Angelina/HumanMyocarditis/data/dataJune24/"
fileNamList <- list.files(path = basedir)

for(i in 1:length(fileNamList)){
  seuratS <- readRDS(paste0(basedir, fileNamList[i]))
  if(exists("seuratM")){
    seuratM <- merge(x = seuratM, y = seuratS)
  }else{
    seuratM <- seuratS
  }
}

remove(seuratS)
table(seuratM$dataset)
table(seuratM$orig.ident)

### load files dataNCR and merge
basedir <- "/Users/immbio/Desktop/Project/Angelina/HumanMyocarditis/data/dataNCR/"
fileNamList <- list.files(path = basedir)

for(i in 1:length(fileNamList)){
  seuratS <- readRDS(paste0(basedir, fileNamList[i]))
  if(exists("seuratM")){
    seuratM <- merge(x = seuratM, y = seuratS)
  }else{
    seuratM <- seuratS
  }
}

remove(seuratS)
table(seuratM$dataset)
table(seuratM$orig.ident)
```

## add metadata
```{r add metadata, eval=FALSE, include=TRUE}
### add any type of metadata
### patient
HH_1 <- c("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM")
HH_2 <- c("o28576_1_09-9_20220525_Hu_nucseq_Graz_9_HH_GEM")
HH_3 <- c("o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM")
HH_4 <- c("o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM")
HH_5 <- c("o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM")
HH_6 <- c("o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM")
HH_7 <- c("o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM")
HH_8 <- c("o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM")
HH_9 <- c("o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM")
HH_10 <- c("o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM")
HH_11 <- c("o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM")

pat_39 <- c("347741_6-6_20240326_Hu_nucseq_Immpath_AM39_0", "348751_1-6_20240326_Hu_nucseq_Immpath_AM39_0_rep")
pat_18 <- c("353921_28-28_20240529_Hu_nucseq_Immpath_EMB18")
pat_24 <- c("353921_29-29_20240529_Hu_nucseq_Immpath_EMB24")
pat_25 <- c("353921_30-30_20240529_Hu_nucseq_Immpath_EMB25")
pat_27 <- c("353921_31-31_20240529_Hu_nucseq_Immpath_EMB27")
pat_29 <- c("353921_32-32_20240529_Hu_nucseq_Immpath_EMB29")
pat_30 <- c("353921_33-33_20240529_Hu_nucseq_Immpath_EMB30")
pat_35 <- c("353921_34-34_20240529_Hu_nucseq_Immpath_EMB35")
pat_37 <- c("353921_35-35_20240529_Hu_nucseq_Immpath_EMB37")

pat_NCR30 <- c("o27533_1_11-11_20220203_Hu_nucseq_EMB30_GEM")
pat_NCR31 <- c("o27533_1_12-12_20220203_Hu_nucseq_EMB31_GEM")
pat_NCR32 <- c("o27936_1_7-7_20220309_Hu_nucseq_EMB32_GEM")
pat_NCR33 <- c("o292731_3-3_20220818_Hu_nucseq_SG_33_EMB_GEM")
pat_NCR34 <- c("o292731_4-4_20220818_Hu_nucseq_SG_34_EMB_GEM")
pat_NCRGraz1 <- c("o28576_1_01-1_20220525_Hu_nucseq_Graz_1_EMB_GEM")
pat_NCRGraz2 <- c("o28576_1_02-2_20220525_Hu_nucseq_Graz_2_EMB_GEM")
pat_NCRGraz15 <- c("o294781_06-6_20220912_Hu_nucseq_Graz_15_EMB_GEM")

seuratM$patient <- "pat_nr"
seuratM$patient[which(seuratM$dataset %in% pat_39)] <- "Immpath39"
seuratM$patient[which(seuratM$dataset %in% pat_18)] <- "Immpath18"
seuratM$patient[which(seuratM$dataset %in% pat_24)] <- "Immpath24"
seuratM$patient[which(seuratM$dataset %in% pat_25)] <- "Immpath25"
seuratM$patient[which(seuratM$dataset %in% pat_27)] <- "Immpath27"
seuratM$patient[which(seuratM$dataset %in% pat_29)] <- "Immpath29"
seuratM$patient[which(seuratM$dataset %in% pat_30)] <- "Immpath30"
seuratM$patient[which(seuratM$dataset %in% pat_35)] <- "Immpath35"
seuratM$patient[which(seuratM$dataset %in% pat_37)] <- "Immpath37"

seuratM$patient[which(seuratM$dataset %in% pat_NCR30)] <- "NCR30"
seuratM$patient[which(seuratM$dataset %in% pat_NCR31)] <- "NCR31"
seuratM$patient[which(seuratM$dataset %in% pat_NCR32)] <- "NCR32"
seuratM$patient[which(seuratM$dataset %in% pat_NCR33)] <- "NCR33"
seuratM$patient[which(seuratM$dataset %in% pat_NCR34)] <- "NCR34"
seuratM$patient[which(seuratM$dataset %in% pat_NCRGraz1)] <- "NCRGraz1"
seuratM$patient[which(seuratM$dataset %in% pat_NCRGraz2)] <- "NCRGraz2"
seuratM$patient[which(seuratM$dataset %in% pat_NCRGraz15)] <- "NCRGraz15"

seuratM$patient[which(seuratM$dataset %in% HH_1)] <- "HH1"
seuratM$patient[which(seuratM$dataset %in% HH_2)] <- "HH2"
seuratM$patient[which(seuratM$dataset %in% HH_3)] <- "HH3"
seuratM$patient[which(seuratM$dataset %in% HH_4)] <- "HH4"
seuratM$patient[which(seuratM$dataset %in% HH_5)] <- "HH5"
seuratM$patient[which(seuratM$dataset %in% HH_6)] <- "HH6"
seuratM$patient[which(seuratM$dataset %in% HH_7)] <- "HH7"
seuratM$patient[which(seuratM$dataset %in% HH_8)] <- "HH8"
seuratM$patient[which(seuratM$dataset %in% HH_9)] <- "HH9"
seuratM$patient[which(seuratM$dataset %in% HH_10)] <- "HH10"
seuratM$patient[which(seuratM$dataset %in% HH_11)] <- "HH2"

table(seuratM$patient)
table(seuratM$orig.ident)

#### cond
#healthy
healthy <- c("o28576_1_08-8_20220525_Hu_nucseq_Graz_8_HH_GEM","o28576_1_10-10_20220525_Hu_nucseq_Graz_10_HH_GEM","o28576_1_11-11_20220525_Hu_nucseq_Graz_11_HH_GEM", "o28576_1_12-12_20220525_Hu_nucseq_Graz_12_HH_GEM","o292731_1-1_20220818_Hu_nucseq_Graz_9_HH_GEM","o292731_2-2_20220818_Hu_nucseq_Graz_13_HH_GEM", "o294781_01-1_20220912_Hu_nucseq_Graz_21_HH_GEM", "o294781_02-2_20220912_Hu_nucseq_Graz_22_HH_GEM", "o294781_03-3_20220912_Hu_nucseq_Graz_23_HH_GEM", "o294781_04-4_20220912_Hu_nucseq_Graz_24_HH_GEM", "o28576_1_09-9_20220525_Hu_nucseq_Graz_9_HH_GEM")

seuratM$cond <- "myocarditis"
seuratM$cond[which(seuratM$dataset %in% healthy)] <- "healthy"
table(seuratM$cond)
```

## rerun seurat
```{r rerun seurat, eval=FALSE, include=TRUE}
#rerun seurat
seuratM <- NormalizeData (object = seuratM)
seuratM <- FindVariableFeatures(object = seuratM)
seuratM <- ScaleData(object = seuratM, verbose = TRUE)
seuratM <- RunPCA(object=seuratM, npcs = 30, verbose = FALSE)
seuratM <- RunTSNE(object=seuratM, reduction="pca", dims = 1:20, check_duplicates = FALSE)
seuratM <- RunUMAP(object=seuratM, reduction="pca", dims = 1:20)
seuratM <- FindNeighbors(object = seuratM, reduction = "pca", dims= 1:20)

res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratM <- FindClusters(object = seuratM, resolution = res[i], random.seed = 1234)
}
```

```{r save merged seurat object, eval=FALSE, include=TRUE}
### save seurat object
saveRDS(seuratM, file="/Users/immbio/Desktop/Project/Angelina/HumanMyocarditis/data/ImmpathMyocarditis_allmerged_seurat.rds")
```

############################## end pre-processing ##############################

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/HumanMyocarditis/data/ImmpathMyocarditis_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
table(seuratM$dataset)
table(seuratM$RNA_snn_res.0.25)
table(seuratM$orig.ident)
```

##set color vectors 
```{r set color vector}
colcond <- c("#355C7D", "#B45B5C")
names(colcond) <- unique(seuratM$cond)

col0.25 <- c("#67001f", "#b2182b", "#d6604d", "#f4a582", "#dfc27d","#003c30","#01665e","#35978f","#c7eae5","#4d4d4d","#1a1a1a","#8c510a", "#355C7D","#779d8d","#3288BD", "#5E4FA2" ,"#BEAED4") 
names(col0.25) <- c("0" ,"1", "2", "3", "4", "5", "6", "7", "8", "9", "10","11", "12", "13", "14", "15", "16")
```

## plot cell numbers
```{r cellnumber circle}
cell_count <- data.frame(table(seuratM$patient))
colnames(cell_count) <- c("patient", "Freq")
hsize <- 1.5

ggplot(cell_count, aes(x = hsize, y = Freq, fill = patient)) +
  #scale_fill_manual(values = colpat2) +
  geom_col(color = "white") +
  coord_polar(theta = "y") +
  xlim(c(0.2, hsize + 0.5)) +
  theme_void() +
  ggtitle("cell number") +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  geom_text(aes(label = Freq), position = position_stack(vjust = 0.5))
```

## QC merged 
```{r QC merged}
### QC merged
# Extract meta.data from the Seurat object
meta.data <- seuratM@meta.data
# Create the density plot
ptotalpat <- ggplot(data = meta.data, aes(x = total, color = patient, fill = patient)) +
  geom_density(alpha = 0.2) +
  #scale_fill_manual(values = colpat) +
  #scale_color_manual(values = colpat) +
  theme_classic() +
  scale_x_log10() +
  ylab("density") +
  geom_vline(xintercept = 100)

pdetectedpat <- ggplot(data = meta.data, aes(x = detected, color = patient, fill = patient)) +
  geom_density(alpha = 0.2) +
  #scale_fill_manual(values = colpat) +
  #scale_color_manual(values = colpat) +
  theme_classic() +
  scale_x_log10() +
  ylab("density") +
  geom_vline(xintercept = 100)

# Return the plots as a list
list(ptotalpat, pdetectedpat)
```

## plot umaps
```{r umap}
Idents(seuratM) <- seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = col0.25, label = TRUE) 

Idents(seuratM) <- seuratM$patient
DimPlot(seuratM, reduction = "umap", pt.size = 0.1) 
DimPlot(seuratM, reduction = "umap", pt.size = 0.1) + theme(legend.position = "null")

Idents(seuratM) <- seuratM$cond
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = colcond) 
```
## plot features
```{r feature plot}
FeaturePlot(seuratM, features = "ENSG00000155657.TTN", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000134571.MYBPC3", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000261371.PECAM1", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000172889.EGFL7", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000110799.VWF", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000137077.CCL21", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000133392.MYH11", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000107796.ACTA2", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000134853.PDGFRA", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000081052.COL4A4", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000081237.PTPRC", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000168685.IL7R", pt.size = 1, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000116824.CD2", pt.size = 1, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM, features = "ENSG00000177575.CD163", pt.size = 1, cols = c("lightgrey", "#BE3144"))
```
## plot umaps subsets
```{r umap subsets}
seurathealthy <- subset(seuratM, cond == "healthy")
seuratmyocarditis <- subset(seuratM, cond == "myocarditis")

Idents(seurathealthy) <- seurathealthy$cond
DimPlot(seurathealthy, reduction = "umap", pt.size = 0.1, cols = colcond) 

Idents(seuratmyocarditis) <- seuratmyocarditis$cond
DimPlot(seuratmyocarditis, reduction = "umap", pt.size = 0.1, cols = colcond) 
```
## rel abundance
```{r rel abundance, fig.height=8, fig.width=10}
###dataset
datList <- NULL
for(con in unique(seuratM$patient)){
  seuratSub <- subset(seuratM, patient==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$RNA_snn_res.0.25)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(patient=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "patient", y= "percent", fill = "Var1", palette = col0.25, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

###cond
datList <- NULL
for(con in unique(seuratM$cond)){
  seuratSub <- subset(seuratM, cond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$RNA_snn_res.0.25)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(cond=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "cond", y= "percent", fill = "Var1", palette = col0.25, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## session info
```{r date and session info}
date()
sessionInfo()
```
